version: "3.8"

services:
  db:
    image: mariadb:latest
    container_name: m347-kn04a-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - m347-kn04b-network

  web:
    image: cameronmeile/m347:latest
    container_name: m347-kn04a-web
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      - m347-kn04b-network

networks:
  m347-kn04b-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.11.0.0/16
          ip_range: 172.11.6.0/24
          gateway: 172.11.6.254
