#cloud-config
# source: https://gist.github.com/syntaqx/9dd3ff11fb3d48b032c84f3e31af9163
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUBo+qnNu5xxM9vfz4C04M36FHxHNrEMdm5TkFj1/SfVtqunlUOeMpu7nFCZZKnX8HYwf/MkjcBiTYAgncxku8grwl6XuW/pcvmb6/ghSIaw4xtRRSzit7omqJ5d8kXB3+Nd1aaMHsjfly4nkaqswhySVXQqr8Hw6DbWVw8jLLVKEE+5NZHY33hJkhJwK4blCllsGpmQaKi1qxjsN0hZOWNK01iJAydwD8t2xJ0NOYbq8Qas5IyPnRN7SPxvEhIP6WLQ6Ym6Dmf8FwNW1cHLTKabgjzt5f/HKUkKS89dPd3fn4nnFli1BOMECGUIvVlOw2pQNri7+04OOfn2FGlqr5 aws-key # teacher
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCcbO03gnkkKf1FlX90wK4ZoTDVdtSJCGtYpoan2K6e1cbyffGC6MfmNPgVp7w2jMSRbxm/AmsRmMhcOAozFEM/u47opZ7hAUivuJHbavlerx2uZU1VcYZ0eFWf+tRKz0lVH++tstSqTAvbCK67s0dIl/W0gnPmO3Vy0UMf9ChF++kdoVblRbEifiSVn2upPGI4NlGAnI2A8C9Z4mpxdC1l2BNasfI15UwMe+Xfr5U85g1WhBjmlCzX6RLUFlppaLaz/Etz+Bfj+tsBm9RJMOKyGfXFryqALb5SrcRSTM9i2LZcmlxAt6idvcREwTsJNnolUQOoKDyutCnb38fAwqcH aws-key # jan
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCG2WoVItWy/mWwDsRlWHRfsR1XKTXdnS44RRg+pdM0OEX2OmbiqxDZKPEUJ9w/2O/y7l/RyZ8JKm4FuJ6+R6vVWJ80XmY67OEj48zR2O9XxK64M9uoI+cQA7yz/FK5twjpplz8BUnYh4AnYWJuhQKItXYcrqBzfkF6eROHjBB6ha52bE87dbNXuz77mc/ILjqEW18Z/2DXtluH4cbFOQ9itgLi8b4n2bybTVpIMQPF1ei5oWGxqYGTq6VVxfLqY7/C05VvDpkoFlZz4DJu2pASU+1gklDThqAd1+3n/ge9gOK2YYXxzjfeM50BJobU5stKZW1V6EAC6rfGR3ecO5JL aws-key # cameron
disable_root: false
package_update: true
package_upgrade: true
groups:
  - docker
system_info:
  default_user:
    groups: [docker]
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - unattended-upgrades
final_message: "The system is finally up, after $UPTIME seconds"
write_files:
  - path: /home/ubuntu/src/db.php
    permissions: "0644"
    content: |
      <?php
        $servername = "m347-kn04b-db";
        $username = "root";
        $password = "123";
        $dbname = "test";

        // Create connection
        $conn = new mysqli($servername, $username, $password);//, $dbname);

        // Check connection
        if ($conn->connect_error) {
            die("Connection failed: " . $conn->connect_error);
        }

        $sql = "SELECT Host, User FROM mysql.user;";
        $result = $conn->query($sql);

        while ($row = $result->fetch_assoc()) {
            echo ($row["Host"] . " / " . $row["User"] . "<br />");
        }

        $conn->close();
      ?>
  - path: /home/ubuntu/src/info.php
    permissions: "0644"
    content: |
      <?php
        phpinfo();
      ?>
  - path: /home/ubuntu/dockerfile
    permissions: "0644"
    content: |
      FROM php:8.0-apache
      WORKDIR /var/www/html/
      COPY src .
      EXPOSE 80
      RUN ["docker-php-ext-install", "mysqli"]
  - path: /home/ubuntu/docker-compose.yml
    permissions: "0644"
    content: |
      version: '3.8'
      name: kn04b-compose
      services:
        database:
          image: mariadb:latest
          container_name: m347-kn04b-db
          ports:
            - "3306:3306"
          environment:
            - MARIADB_ROOT_PASSWORD=123
          networks:
            - kn04b-network
        web:
          build: .
          container_name: m347-kn04b-web
          ports:
            - "80:80"
          depends_on:
            - database
          networks:
            - kn04b-network
      networks:
        kn04b-network:
          driver: bridge
          ipam:
            config:
              - subnet: 172.10.0.0/16
                ip_range: 172.10.5.0/24
                gateway: 172.10.5.254
runcmd:
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  - systemctl enable docker
  - systemctl start docker
  - cd /home/ubuntu
  - sudo docker compose up -d #cloud-config