version: "3.8"

services:
  db:
    image: cameronmeile/m347:mariadb
    # image: cameronmeile/m347:mariadb
    container_name: m347-kn04b-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - 3306:3306
    networks:
      - m347-kn04b-network

  web:
    image: cameronmeile/m347:kn02b
    # image: cameronmeile/m347:mariadb
    container_name: m347-kn04b-web
    build:
      context: ./src/
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      - m347-kn04b-network

networks:
  m347-kn04b-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.11.0.0/16
          ip_range: 172.11.5.0/24
          gateway: 172.11.5.254